import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../Components/shared/Header";
import { Providers } from "@/provider/PageTrasitionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="!scroll-smooth min-h-screen pt-24  flex  flex-col items-center justify-between bg-black/90 text-white overflow-x-hidden"
    >
      <body
        className={
          inter.className + "flex  flex-col items-center justify-between"
        }
      >
        <Header />
        <Providers>{children}</Providers>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
